### PR TITLE
Do not link native library when cross compiling for docs

### LINKED ISSUE #144: Crates that use shaderc at build time fail to build on docs.rs
#130 made shaderc unable to build on docs.rs at all. That's fine for building the crate itself, and crates depending on it, however some crates use shaderc *at build time*. See rust-lang/docs.rs#2329 for the issues this causes and the affected crates.

### PR DESCRIPTION
**Pull request by marc0246**
This fixes #144 by only bailing out on the linking if cross-compilation is going on, which excludes build scripts and proc-macros. I really hate this solution, and I wish there was some other way to go about this, but at least this doesn't penalize any crates in the sense that the dependent library's author doesn't need to do anything. I just pray that this doesn't run into more unforseen complications.

### CODE REVIEW

**Comment by marc0246** [comment]
Is there no way to sign the CLA without revealing my email address?

**Comment by antiagainst** [comment]
LGTM; but wanted to have @chyyran take a look too.

**Comment by chyyran** [comment]
lgtm

**Comment by marc0246** [comment]
Can we please get a patch version bump?

**Comment by antiagainst** [comment]
> Can we please get a patch version bump?

Sure; pushed a new release.

**Comment by marc0246** [comment]
Awesome, thanks a lot!

**Pull request merged**
