### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by BeastLe9enD**
Hey, I updated all submodules, the tests run without error!

### CODE REVIEW

**Comment by antiagainst** [comment]
Thanks for the pull request (and sorry about the delay)! Looks there is an issue in shaderc. I filed a fix here: https://github.com/google/shaderc/pull/1280.

**Comment by BeastLe9enD** [comment]
What OS are you on? On Windows, everything works fine for me!

**Comment by antiagainst** [comment]
> What OS are you on? On Windows, everything works fine for me!

It's the cross compilation build bots failing: https://github.com/google/shaderc-rs/actions/runs/3331419724/jobs/5898768267.

**Comment by antiagainst** [comment]
Hey @BeastLe9enD, https://github.com/google/shaderc/pull/1280 is landed in shaderc. If you can refresh it again (sorry about the trouble!), the tests should be passing I belive. Thanks!

**Comment by BeastLe9enD** [comment]
Yes, it should work now! Thank you!

**Review by antiagainst — APPROVED** [review]

**Comment by Jerrody** [comment]
I think that we can merge it!

**Pull request merged**
